//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 04:31:46 PM UTC 
//


package eu.openaire.oaf.model.base;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fundingParentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fundingParentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice minOccurs="0"&gt;
 *         &lt;element name="funding_level_1" type="{http://namespace.openaire.eu/oaf}fundingType"/&gt;
 *         &lt;element name="funding_level_0" type="{http://namespace.openaire.eu/oaf}fundingType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fundingParentType", propOrder = {
    "fundingLevel1",
    "fundingLevel0"
})
public class FundingParentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "funding_level_1", namespace = "")
    protected FundingType fundingLevel1;
    @XmlElement(name = "funding_level_0", namespace = "")
    protected FundingType fundingLevel0;

    /**
     * Gets the value of the fundingLevel1 property.
     * 
     * @return
     *     possible object is
     *     {@link FundingType }
     *     
     */
    public FundingType getFundingLevel1() {
        return fundingLevel1;
    }

    /**
     * Sets the value of the fundingLevel1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingType }
     *     
     */
    public void setFundingLevel1(FundingType value) {
        this.fundingLevel1 = value;
    }

    /**
     * Gets the value of the fundingLevel0 property.
     * 
     * @return
     *     possible object is
     *     {@link FundingType }
     *     
     */
    public FundingType getFundingLevel0() {
        return fundingLevel0;
    }

    /**
     * Sets the value of the fundingLevel0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingType }
     *     
     */
    public void setFundingLevel0(FundingType value) {
        this.fundingLevel0 = value;
    }

}
