//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 04:31:46 PM UTC 
//


package eu.openaire.oaf.model.base;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for instanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instanceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="license" type="{http://namespace.openaire.eu/oaf}fieldType"/&gt;
 *         &lt;element name="accessright" type="{http://namespace.openaire.eu/oaf}qualifierType"/&gt;
 *         &lt;element name="instancetype" type="{http://namespace.openaire.eu/oaf}qualifierType"/&gt;
 *         &lt;element name="collectedfrom" type="{http://namespace.openaire.eu/oaf}namedIdElementType"/&gt;
 *         &lt;element name="hostedby" type="{http://namespace.openaire.eu/oaf}namedIdElementType"/&gt;
 *         &lt;element name="webresource" type="{http://namespace.openaire.eu/oaf}webresourceType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="distributionlocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dateofacceptance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="processingchargeamount" type="{http://namespace.openaire.eu/oaf}fieldType"/&gt;
 *         &lt;element name="processingchargecurrency" type="{http://namespace.openaire.eu/oaf}fieldType"/&gt;
 *         &lt;element name="refereed" type="{http://namespace.openaire.eu/oaf}fieldType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instanceType", propOrder = {
    "licenseOrAccessrightOrInstancetype"
})
public class InstanceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRefs({
        @XmlElementRef(name = "license", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "accessright", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "instancetype", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "collectedfrom", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "hostedby", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "webresource", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "distributionlocation", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dateofacceptance", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "processingchargeamount", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "processingchargecurrency", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "refereed", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> licenseOrAccessrightOrInstancetype;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the licenseOrAccessrightOrInstancetype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licenseOrAccessrightOrInstancetype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicenseOrAccessrightOrInstancetype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link WebresourceType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getLicenseOrAccessrightOrInstancetype() {
        if (licenseOrAccessrightOrInstancetype == null) {
            licenseOrAccessrightOrInstancetype = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.licenseOrAccessrightOrInstancetype;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
