//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 04:31:46 PM UTC 
//


package eu.openaire.oaf.model.base;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for journalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="journalType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="eissn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="issn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="lissn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ep" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="iss" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="sp" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="vol" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "journalType", propOrder = {
    "value"
})
public class JournalType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlValue
    protected String value;
    @XmlAttribute(name = "eissn")
    @XmlSchemaType(name = "anySimpleType")
    protected String eissn;
    @XmlAttribute(name = "issn")
    @XmlSchemaType(name = "anySimpleType")
    protected String issn;
    @XmlAttribute(name = "lissn")
    @XmlSchemaType(name = "anySimpleType")
    protected String lissn;
    @XmlAttribute(name = "ep")
    @XmlSchemaType(name = "anySimpleType")
    protected String ep;
    @XmlAttribute(name = "iss")
    @XmlSchemaType(name = "anySimpleType")
    protected String iss;
    @XmlAttribute(name = "sp")
    @XmlSchemaType(name = "anySimpleType")
    protected String sp;
    @XmlAttribute(name = "vol")
    @XmlSchemaType(name = "anySimpleType")
    protected String vol;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the eissn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEissn() {
        return eissn;
    }

    /**
     * Sets the value of the eissn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEissn(String value) {
        this.eissn = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssn() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssn(String value) {
        this.issn = value;
    }

    /**
     * Gets the value of the lissn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLissn() {
        return lissn;
    }

    /**
     * Sets the value of the lissn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLissn(String value) {
        this.lissn = value;
    }

    /**
     * Gets the value of the ep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEp() {
        return ep;
    }

    /**
     * Sets the value of the ep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEp(String value) {
        this.ep = value;
    }

    /**
     * Gets the value of the iss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIss() {
        return iss;
    }

    /**
     * Sets the value of the iss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIss(String value) {
        this.iss = value;
    }

    /**
     * Gets the value of the sp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSp() {
        return sp;
    }

    /**
     * Sets the value of the sp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSp(String value) {
        this.sp = value;
    }

    /**
     * Gets the value of the vol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVol() {
        return vol;
    }

    /**
     * Sets the value of the vol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVol(String value) {
        this.vol = value;
    }

}
