//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 04:31:46 PM UTC 
//


package eu.openaire.oaf.model.base;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.openaire.oaf.model.base package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResultCreator_QNAME = new QName("http://namespace.openaire.eu/oaf", "creator");
    private final static QName _ResultResulttype_QNAME = new QName("http://namespace.openaire.eu/oaf", "resulttype");
    private final static QName _ResultLanguage_QNAME = new QName("http://namespace.openaire.eu/oaf", "language");
    private final static QName _ResultCountry_QNAME = new QName("http://namespace.openaire.eu/oaf", "country");
    private final static QName _ResultSubject_QNAME = new QName("http://namespace.openaire.eu/oaf", "subject");
    private final static QName _ResultTitle_QNAME = new QName("http://namespace.openaire.eu/oaf", "title");
    private final static QName _ResultRelevantdate_QNAME = new QName("http://namespace.openaire.eu/oaf", "relevantdate");
    private final static QName _ResultDescription_QNAME = new QName("http://namespace.openaire.eu/oaf", "description");
    private final static QName _ResultDateofacceptance_QNAME = new QName("http://namespace.openaire.eu/oaf", "dateofacceptance");
    private final static QName _ResultPublisher_QNAME = new QName("http://namespace.openaire.eu/oaf", "publisher");
    private final static QName _ResultEmbargoenddate_QNAME = new QName("http://namespace.openaire.eu/oaf", "embargoenddate");
    private final static QName _ResultSource_QNAME = new QName("http://namespace.openaire.eu/oaf", "source");
    private final static QName _ResultFormat_QNAME = new QName("http://namespace.openaire.eu/oaf", "format");
    private final static QName _ResultContributor_QNAME = new QName("http://namespace.openaire.eu/oaf", "contributor");
    private final static QName _ResultResourcetype_QNAME = new QName("http://namespace.openaire.eu/oaf", "resourcetype");
    private final static QName _ResultCoverage_QNAME = new QName("http://namespace.openaire.eu/oaf", "coverage");
    private final static QName _ResultBestaccessright_QNAME = new QName("http://namespace.openaire.eu/oaf", "bestaccessright");
    private final static QName _ResultJournal_QNAME = new QName("http://namespace.openaire.eu/oaf", "journal");
    private final static QName _ResultPid_QNAME = new QName("http://namespace.openaire.eu/oaf", "pid");
    private final static QName _ResultDevice_QNAME = new QName("http://namespace.openaire.eu/oaf", "device");
    private final static QName _ResultSize_QNAME = new QName("http://namespace.openaire.eu/oaf", "size");
    private final static QName _ResultVersion_QNAME = new QName("http://namespace.openaire.eu/oaf", "version");
    private final static QName _ResultLastmetadataupdate_QNAME = new QName("http://namespace.openaire.eu/oaf", "lastmetadataupdate");
    private final static QName _ResultMetadataversionnumber_QNAME = new QName("http://namespace.openaire.eu/oaf", "metadataversionnumber");
    private final static QName _ResultOriginalId_QNAME = new QName("http://namespace.openaire.eu/oaf", "originalId");
    private final static QName _ResultCollectedfrom_QNAME = new QName("http://namespace.openaire.eu/oaf", "collectedfrom");
    private final static QName _ResultContext_QNAME = new QName("http://namespace.openaire.eu/oaf", "context");
    private final static QName _ResultRels_QNAME = new QName("http://namespace.openaire.eu/oaf", "rels");
    private final static QName _ResultInstances_QNAME = new QName("http://namespace.openaire.eu/oaf", "instances");
    private final static QName _ResultCitations_QNAME = new QName("http://namespace.openaire.eu/oaf", "citations");
    private final static QName _OrganizationLegalname_QNAME = new QName("http://namespace.openaire.eu/oaf", "legalname");
    private final static QName _OrganizationLegalshortname_QNAME = new QName("http://namespace.openaire.eu/oaf", "legalshortname");
    private final static QName _OrganizationLogourl_QNAME = new QName("http://namespace.openaire.eu/oaf", "logourl");
    private final static QName _OrganizationWebsiteurl_QNAME = new QName("http://namespace.openaire.eu/oaf", "websiteurl");
    private final static QName _DatasourceNamespaceprefix_QNAME = new QName("http://namespace.openaire.eu/oaf", "namespaceprefix");
    private final static QName _DatasourceOfficialname_QNAME = new QName("http://namespace.openaire.eu/oaf", "officialname");
    private final static QName _DatasourceEnglishname_QNAME = new QName("http://namespace.openaire.eu/oaf", "englishname");
    private final static QName _DatasourceContactemail_QNAME = new QName("http://namespace.openaire.eu/oaf", "contactemail");
    private final static QName _DatasourceDatasourcetype_QNAME = new QName("http://namespace.openaire.eu/oaf", "datasourcetype");
    private final static QName _DatasourceOpenairecompatibility_QNAME = new QName("http://namespace.openaire.eu/oaf", "openairecompatibility");
    private final static QName _DatasourceDateofvalidation_QNAME = new QName("http://namespace.openaire.eu/oaf", "dateofvalidation");
    private final static QName _DatasourceLatitude_QNAME = new QName("http://namespace.openaire.eu/oaf", "latitude");
    private final static QName _DatasourceLongitude_QNAME = new QName("http://namespace.openaire.eu/oaf", "longitude");
    private final static QName _DatasourceSubjects_QNAME = new QName("http://namespace.openaire.eu/oaf", "subjects");
    private final static QName _ProjectCode_QNAME = new QName("", "code");
    private final static QName _ProjectTitle_QNAME = new QName("", "title");
    private final static QName _ProjectAcronym_QNAME = new QName("", "acronym");
    private final static QName _ProjectCallidentifier_QNAME = new QName("", "callidentifier");
    private final static QName _ProjectContactfullname_QNAME = new QName("", "contactfullname");
    private final static QName _ProjectContactfax_QNAME = new QName("", "contactfax");
    private final static QName _ProjectContactphone_QNAME = new QName("", "contactphone");
    private final static QName _ProjectContactemail_QNAME = new QName("", "contactemail");
    private final static QName _ProjectContracttype_QNAME = new QName("", "contracttype");
    private final static QName _ProjectKeywords_QNAME = new QName("", "keywords");
    private final static QName _ProjectWebsiteurl_QNAME = new QName("", "websiteurl");
    private final static QName _ProjectStartdate_QNAME = new QName("", "startdate");
    private final static QName _ProjectEnddate_QNAME = new QName("", "enddate");
    private final static QName _ProjectDuration_QNAME = new QName("", "duration");
    private final static QName _ProjectEcsc39_QNAME = new QName("", "ecsc39");
    private final static QName _ProjectOamandatepublications_QNAME = new QName("", "oamandatepublications");
    private final static QName _ProjectEcarticle293_QNAME = new QName("", "ecarticle29_3");
    private final static QName _ProjectSubjects_QNAME = new QName("", "subjects");
    private final static QName _ProjectFundingtree_QNAME = new QName("", "fundingtree");
    private final static QName _ProjectOriginalId_QNAME = new QName("", "originalId");
    private final static QName _ProjectCollectedfrom_QNAME = new QName("", "collectedfrom");
    private final static QName _ProjectPid_QNAME = new QName("", "pid");
    private final static QName _ProjectRels_QNAME = new QName("", "rels");
    private final static QName _InstanceTypeLicense_QNAME = new QName("http://namespace.openaire.eu/oaf", "license");
    private final static QName _InstanceTypeAccessright_QNAME = new QName("http://namespace.openaire.eu/oaf", "accessright");
    private final static QName _InstanceTypeInstancetype_QNAME = new QName("http://namespace.openaire.eu/oaf", "instancetype");
    private final static QName _InstanceTypeHostedby_QNAME = new QName("http://namespace.openaire.eu/oaf", "hostedby");
    private final static QName _InstanceTypeWebresource_QNAME = new QName("http://namespace.openaire.eu/oaf", "webresource");
    private final static QName _InstanceTypeDistributionlocation_QNAME = new QName("http://namespace.openaire.eu/oaf", "distributionlocation");
    private final static QName _InstanceTypeProcessingchargeamount_QNAME = new QName("http://namespace.openaire.eu/oaf", "processingchargeamount");
    private final static QName _InstanceTypeProcessingchargecurrency_QNAME = new QName("http://namespace.openaire.eu/oaf", "processingchargecurrency");
    private final static QName _InstanceTypeRefereed_QNAME = new QName("http://namespace.openaire.eu/oaf", "refereed");
    private final static QName _RelTypeTo_QNAME = new QName("http://namespace.openaire.eu/oaf", "to");
    private final static QName _RelTypeUrl_QNAME = new QName("http://namespace.openaire.eu/oaf", "url");
    private final static QName _RelTypeSimilarity_QNAME = new QName("http://namespace.openaire.eu/oaf", "similarity");
    private final static QName _RelTypeType_QNAME = new QName("http://namespace.openaire.eu/oaf", "type");
    private final static QName _RelTypeCode_QNAME = new QName("http://namespace.openaire.eu/oaf", "code");
    private final static QName _RelTypeAcronym_QNAME = new QName("http://namespace.openaire.eu/oaf", "acronym");
    private final static QName _RelTypeContracttype_QNAME = new QName("http://namespace.openaire.eu/oaf", "contracttype");
    private final static QName _RelTypeFunding_QNAME = new QName("http://namespace.openaire.eu/oaf", "funding");
    private final static QName _FundingTreeTypeFundingLevel2_QNAME = new QName("", "funding_level_2");
    private final static QName _FundingTreeTypeFundingLevel1_QNAME = new QName("", "funding_level_1");
    private final static QName _FundingTreeTypeFundingLevel0_QNAME = new QName("", "funding_level_0");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.openaire.oaf.model.base
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link CitationsType }
     * 
     */
    public CitationsType createCitationsType() {
        return new CitationsType();
    }

    /**
     * Create an instance of {@link CitationsType.Citation }
     * 
     */
    public CitationsType.Citation createCitationsTypeCitation() {
        return new CitationsType.Citation();
    }

    /**
     * Create an instance of {@link Result.Creator }
     * 
     */
    public Result.Creator createResultCreator() {
        return new Result.Creator();
    }

    /**
     * Create an instance of {@link QualifierType }
     * 
     */
    public QualifierType createQualifierType() {
        return new QualifierType();
    }

    /**
     * Create an instance of {@link DataInfoType }
     * 
     */
    public DataInfoType createDataInfoType() {
        return new DataInfoType();
    }

    /**
     * Create an instance of {@link StructuredPropertyElementType }
     * 
     */
    public StructuredPropertyElementType createStructuredPropertyElementType() {
        return new StructuredPropertyElementType();
    }

    /**
     * Create an instance of {@link JournalType }
     * 
     */
    public JournalType createJournalType() {
        return new JournalType();
    }

    /**
     * Create an instance of {@link NamedIdElementType }
     * 
     */
    public NamedIdElementType createNamedIdElementType() {
        return new NamedIdElementType();
    }

    /**
     * Create an instance of {@link ContextType }
     * 
     */
    public ContextType createContextType() {
        return new ContextType();
    }

    /**
     * Create an instance of {@link RelsType }
     * 
     */
    public RelsType createRelsType() {
        return new RelsType();
    }

    /**
     * Create an instance of {@link InstancesType }
     * 
     */
    public InstancesType createInstancesType() {
        return new InstancesType();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link Datasource }
     * 
     */
    public Datasource createDatasource() {
        return new Datasource();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link FundingTreeType }
     * 
     */
    public FundingTreeType createFundingTreeType() {
        return new FundingTreeType();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link FieldType }
     * 
     */
    public FieldType createFieldType() {
        return new FieldType();
    }

    /**
     * Create an instance of {@link LabeledIdElementType }
     * 
     */
    public LabeledIdElementType createLabeledIdElementType() {
        return new LabeledIdElementType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link ConceptType }
     * 
     */
    public ConceptType createConceptType() {
        return new ConceptType();
    }

    /**
     * Create an instance of {@link RelType }
     * 
     */
    public RelType createRelType() {
        return new RelType();
    }

    /**
     * Create an instance of {@link RelToType }
     * 
     */
    public RelToType createRelToType() {
        return new RelToType();
    }

    /**
     * Create an instance of {@link FundingFlatType }
     * 
     */
    public FundingFlatType createFundingFlatType() {
        return new FundingFlatType();
    }

    /**
     * Create an instance of {@link FunderFlatType }
     * 
     */
    public FunderFlatType createFunderFlatType() {
        return new FunderFlatType();
    }

    /**
     * Create an instance of {@link NamedFundingLevel }
     * 
     */
    public NamedFundingLevel createNamedFundingLevel() {
        return new NamedFundingLevel();
    }

    /**
     * Create an instance of {@link ExternalreferenceType }
     * 
     */
    public ExternalreferenceType createExternalreferenceType() {
        return new ExternalreferenceType();
    }

    /**
     * Create an instance of {@link InstanceType }
     * 
     */
    public InstanceType createInstanceType() {
        return new InstanceType();
    }

    /**
     * Create an instance of {@link WebresourceType }
     * 
     */
    public WebresourceType createWebresourceType() {
        return new WebresourceType();
    }

    /**
     * Create an instance of {@link FundingType }
     * 
     */
    public FundingType createFundingType() {
        return new FundingType();
    }

    /**
     * Create an instance of {@link FundingParentType }
     * 
     */
    public FundingParentType createFundingParentType() {
        return new FundingParentType();
    }

    /**
     * Create an instance of {@link FunderType }
     * 
     */
    public FunderType createFunderType() {
        return new FunderType();
    }

    /**
     * Create an instance of {@link CitationsType.Citation.Id }
     * 
     */
    public CitationsType.Citation.Id createCitationsTypeCitationId() {
        return new CitationsType.Citation.Id();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Result.Creator }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Result.Creator }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "creator", scope = Result.class)
    public JAXBElement<Result.Creator> createResultCreator(Result.Creator value) {
        return new JAXBElement<Result.Creator>(_ResultCreator_QNAME, Result.Creator.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "resulttype", scope = Result.class)
    public JAXBElement<QualifierType> createResultResulttype(QualifierType value) {
        return new JAXBElement<QualifierType>(_ResultResulttype_QNAME, QualifierType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "language", scope = Result.class)
    public JAXBElement<QualifierType> createResultLanguage(QualifierType value) {
        return new JAXBElement<QualifierType>(_ResultLanguage_QNAME, QualifierType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataInfoType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataInfoType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "country", scope = Result.class)
    public JAXBElement<DataInfoType> createResultCountry(DataInfoType value) {
        return new JAXBElement<DataInfoType>(_ResultCountry_QNAME, DataInfoType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "subject", scope = Result.class)
    public JAXBElement<StructuredPropertyElementType> createResultSubject(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_ResultSubject_QNAME, StructuredPropertyElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "title", scope = Result.class)
    public JAXBElement<StructuredPropertyElementType> createResultTitle(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_ResultTitle_QNAME, StructuredPropertyElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "relevantdate", scope = Result.class)
    public JAXBElement<StructuredPropertyElementType> createResultRelevantdate(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_ResultRelevantdate_QNAME, StructuredPropertyElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "description", scope = Result.class)
    public JAXBElement<String> createResultDescription(String value) {
        return new JAXBElement<String>(_ResultDescription_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "dateofacceptance", scope = Result.class)
    public JAXBElement<String> createResultDateofacceptance(String value) {
        return new JAXBElement<String>(_ResultDateofacceptance_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "publisher", scope = Result.class)
    public JAXBElement<String> createResultPublisher(String value) {
        return new JAXBElement<String>(_ResultPublisher_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "embargoenddate", scope = Result.class)
    public JAXBElement<String> createResultEmbargoenddate(String value) {
        return new JAXBElement<String>(_ResultEmbargoenddate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "source", scope = Result.class)
    public JAXBElement<String> createResultSource(String value) {
        return new JAXBElement<String>(_ResultSource_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "format", scope = Result.class)
    public JAXBElement<String> createResultFormat(String value) {
        return new JAXBElement<String>(_ResultFormat_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "contributor", scope = Result.class)
    public JAXBElement<String> createResultContributor(String value) {
        return new JAXBElement<String>(_ResultContributor_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "resourcetype", scope = Result.class)
    public JAXBElement<QualifierType> createResultResourcetype(QualifierType value) {
        return new JAXBElement<QualifierType>(_ResultResourcetype_QNAME, QualifierType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "coverage", scope = Result.class)
    public JAXBElement<String> createResultCoverage(String value) {
        return new JAXBElement<String>(_ResultCoverage_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "bestaccessright", scope = Result.class)
    public JAXBElement<QualifierType> createResultBestaccessright(QualifierType value) {
        return new JAXBElement<QualifierType>(_ResultBestaccessright_QNAME, QualifierType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JournalType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JournalType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "journal", scope = Result.class)
    public JAXBElement<JournalType> createResultJournal(JournalType value) {
        return new JAXBElement<JournalType>(_ResultJournal_QNAME, JournalType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Result.class)
    public JAXBElement<StructuredPropertyElementType> createResultPid(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_ResultPid_QNAME, StructuredPropertyElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "device", scope = Result.class)
    public JAXBElement<String> createResultDevice(String value) {
        return new JAXBElement<String>(_ResultDevice_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "size", scope = Result.class)
    public JAXBElement<String> createResultSize(String value) {
        return new JAXBElement<String>(_ResultSize_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "version", scope = Result.class)
    public JAXBElement<String> createResultVersion(String value) {
        return new JAXBElement<String>(_ResultVersion_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "lastmetadataupdate", scope = Result.class)
    public JAXBElement<String> createResultLastmetadataupdate(String value) {
        return new JAXBElement<String>(_ResultLastmetadataupdate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "metadataversionnumber", scope = Result.class)
    public JAXBElement<String> createResultMetadataversionnumber(String value) {
        return new JAXBElement<String>(_ResultMetadataversionnumber_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Result.class)
    public JAXBElement<String> createResultOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Result.class)
    public JAXBElement<NamedIdElementType> createResultCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ContextType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "context", scope = Result.class)
    public JAXBElement<ContextType> createResultContext(ContextType value) {
        return new JAXBElement<ContextType>(_ResultContext_QNAME, ContextType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Result.class)
    public JAXBElement<RelsType> createResultRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstancesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InstancesType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "instances", scope = Result.class)
    public JAXBElement<InstancesType> createResultInstances(InstancesType value) {
        return new JAXBElement<InstancesType>(_ResultInstances_QNAME, InstancesType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CitationsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CitationsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "citations", scope = Result.class)
    public JAXBElement<CitationsType> createResultCitations(CitationsType value) {
        return new JAXBElement<CitationsType>(_ResultCitations_QNAME, CitationsType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalname", scope = Organization.class)
    public JAXBElement<String> createOrganizationLegalname(String value) {
        return new JAXBElement<String>(_OrganizationLegalname_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalshortname", scope = Organization.class)
    public JAXBElement<String> createOrganizationLegalshortname(String value) {
        return new JAXBElement<String>(_OrganizationLegalshortname_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "logourl", scope = Organization.class)
    public JAXBElement<String> createOrganizationLogourl(String value) {
        return new JAXBElement<String>(_OrganizationLogourl_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Organization.class)
    public JAXBElement<String> createOrganizationOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "websiteurl", scope = Organization.class)
    public JAXBElement<String> createOrganizationWebsiteurl(String value) {
        return new JAXBElement<String>(_OrganizationWebsiteurl_QNAME, String.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "country", scope = Organization.class)
    public JAXBElement<QualifierType> createOrganizationCountry(QualifierType value) {
        return new JAXBElement<QualifierType>(_ResultCountry_QNAME, QualifierType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Organization.class)
    public JAXBElement<NamedIdElementType> createOrganizationCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Organization.class)
    public JAXBElement<StructuredPropertyElementType> createOrganizationPid(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_ResultPid_QNAME, StructuredPropertyElementType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Organization.class)
    public JAXBElement<RelsType> createOrganizationRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "namespaceprefix", scope = Datasource.class)
    public JAXBElement<String> createDatasourceNamespaceprefix(String value) {
        return new JAXBElement<String>(_DatasourceNamespaceprefix_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "officialname", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOfficialname(String value) {
        return new JAXBElement<String>(_DatasourceOfficialname_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "englishname", scope = Datasource.class)
    public JAXBElement<String> createDatasourceEnglishname(String value) {
        return new JAXBElement<String>(_DatasourceEnglishname_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "websiteurl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceWebsiteurl(String value) {
        return new JAXBElement<String>(_OrganizationWebsiteurl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "logourl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLogourl(String value) {
        return new JAXBElement<String>(_OrganizationLogourl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "contactemail", scope = Datasource.class)
    public JAXBElement<String> createDatasourceContactemail(String value) {
        return new JAXBElement<String>(_DatasourceContactemail_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "datasourcetype", scope = Datasource.class)
    public JAXBElement<QualifierType> createDatasourceDatasourcetype(QualifierType value) {
        return new JAXBElement<QualifierType>(_DatasourceDatasourcetype_QNAME, QualifierType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "openairecompatibility", scope = Datasource.class)
    public JAXBElement<QualifierType> createDatasourceOpenairecompatibility(QualifierType value) {
        return new JAXBElement<QualifierType>(_DatasourceOpenairecompatibility_QNAME, QualifierType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "dateofvalidation", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDateofvalidation(String value) {
        return new JAXBElement<String>(_DatasourceDateofvalidation_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "latitude", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLatitude(String value) {
        return new JAXBElement<String>(_DatasourceLatitude_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "longitude", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLongitude(String value) {
        return new JAXBElement<String>(_DatasourceLongitude_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "description", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDescription(String value) {
        return new JAXBElement<String>(_ResultDescription_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "subjects", scope = Datasource.class)
    public JAXBElement<StructuredPropertyElementType> createDatasourceSubjects(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_DatasourceSubjects_QNAME, StructuredPropertyElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "originalId", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = Datasource.class)
    public JAXBElement<NamedIdElementType> createDatasourceCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = Datasource.class)
    public JAXBElement<StructuredPropertyElementType> createDatasourcePid(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_ResultPid_QNAME, StructuredPropertyElementType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "rels", scope = Datasource.class)
    public JAXBElement<RelsType> createDatasourceRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "code", scope = Project.class)
    public JAXBElement<String> createProjectCode(String value) {
        return new JAXBElement<String>(_ProjectCode_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "title", scope = Project.class)
    public JAXBElement<String> createProjectTitle(String value) {
        return new JAXBElement<String>(_ProjectTitle_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "acronym", scope = Project.class)
    public JAXBElement<String> createProjectAcronym(String value) {
        return new JAXBElement<String>(_ProjectAcronym_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "callidentifier", scope = Project.class)
    public JAXBElement<String> createProjectCallidentifier(String value) {
        return new JAXBElement<String>(_ProjectCallidentifier_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "contactfullname", scope = Project.class)
    public JAXBElement<String> createProjectContactfullname(String value) {
        return new JAXBElement<String>(_ProjectContactfullname_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "contactfax", scope = Project.class)
    public JAXBElement<String> createProjectContactfax(String value) {
        return new JAXBElement<String>(_ProjectContactfax_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "contactphone", scope = Project.class)
    public JAXBElement<String> createProjectContactphone(String value) {
        return new JAXBElement<String>(_ProjectContactphone_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "contactemail", scope = Project.class)
    public JAXBElement<String> createProjectContactemail(String value) {
        return new JAXBElement<String>(_ProjectContactemail_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "contracttype", scope = Project.class)
    public JAXBElement<QualifierType> createProjectContracttype(QualifierType value) {
        return new JAXBElement<QualifierType>(_ProjectContracttype_QNAME, QualifierType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "keywords", scope = Project.class)
    public JAXBElement<String> createProjectKeywords(String value) {
        return new JAXBElement<String>(_ProjectKeywords_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "websiteurl", scope = Project.class)
    public JAXBElement<String> createProjectWebsiteurl(String value) {
        return new JAXBElement<String>(_ProjectWebsiteurl_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "startdate", scope = Project.class)
    public JAXBElement<String> createProjectStartdate(String value) {
        return new JAXBElement<String>(_ProjectStartdate_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "enddate", scope = Project.class)
    public JAXBElement<String> createProjectEnddate(String value) {
        return new JAXBElement<String>(_ProjectEnddate_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "duration", scope = Project.class)
    public JAXBElement<String> createProjectDuration(String value) {
        return new JAXBElement<String>(_ProjectDuration_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ecsc39", scope = Project.class)
    public JAXBElement<String> createProjectEcsc39(String value) {
        return new JAXBElement<String>(_ProjectEcsc39_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "oamandatepublications", scope = Project.class)
    public JAXBElement<Boolean> createProjectOamandatepublications(Boolean value) {
        return new JAXBElement<Boolean>(_ProjectOamandatepublications_QNAME, Boolean.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ecarticle29_3", scope = Project.class)
    public JAXBElement<String> createProjectEcarticle293(String value) {
        return new JAXBElement<String>(_ProjectEcarticle293_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "subjects", scope = Project.class)
    public JAXBElement<QualifierType> createProjectSubjects(QualifierType value) {
        return new JAXBElement<QualifierType>(_ProjectSubjects_QNAME, QualifierType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingTreeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundingTreeType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "fundingtree", scope = Project.class)
    public JAXBElement<FundingTreeType> createProjectFundingtree(FundingTreeType value) {
        return new JAXBElement<FundingTreeType>(_ProjectFundingtree_QNAME, FundingTreeType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "originalId", scope = Project.class)
    public JAXBElement<String> createProjectOriginalId(String value) {
        return new JAXBElement<String>(_ProjectOriginalId_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "collectedfrom", scope = Project.class)
    public JAXBElement<NamedIdElementType> createProjectCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ProjectCollectedfrom_QNAME, NamedIdElementType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "pid", scope = Project.class)
    public JAXBElement<QualifierType> createProjectPid(QualifierType value) {
        return new JAXBElement<QualifierType>(_ProjectPid_QNAME, QualifierType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "rels", scope = Project.class)
    public JAXBElement<RelsType> createProjectRels(RelsType value) {
        return new JAXBElement<RelsType>(_ProjectRels_QNAME, RelsType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "license", scope = InstanceType.class)
    public JAXBElement<FieldType> createInstanceTypeLicense(FieldType value) {
        return new JAXBElement<FieldType>(_InstanceTypeLicense_QNAME, FieldType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "accessright", scope = InstanceType.class)
    public JAXBElement<QualifierType> createInstanceTypeAccessright(QualifierType value) {
        return new JAXBElement<QualifierType>(_InstanceTypeAccessright_QNAME, QualifierType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "instancetype", scope = InstanceType.class)
    public JAXBElement<QualifierType> createInstanceTypeInstancetype(QualifierType value) {
        return new JAXBElement<QualifierType>(_InstanceTypeInstancetype_QNAME, QualifierType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = InstanceType.class)
    public JAXBElement<NamedIdElementType> createInstanceTypeCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "hostedby", scope = InstanceType.class)
    public JAXBElement<NamedIdElementType> createInstanceTypeHostedby(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_InstanceTypeHostedby_QNAME, NamedIdElementType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebresourceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WebresourceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "webresource", scope = InstanceType.class)
    public JAXBElement<WebresourceType> createInstanceTypeWebresource(WebresourceType value) {
        return new JAXBElement<WebresourceType>(_InstanceTypeWebresource_QNAME, WebresourceType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "distributionlocation", scope = InstanceType.class)
    public JAXBElement<String> createInstanceTypeDistributionlocation(String value) {
        return new JAXBElement<String>(_InstanceTypeDistributionlocation_QNAME, String.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "dateofacceptance", scope = InstanceType.class)
    public JAXBElement<String> createInstanceTypeDateofacceptance(String value) {
        return new JAXBElement<String>(_ResultDateofacceptance_QNAME, String.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "processingchargeamount", scope = InstanceType.class)
    public JAXBElement<FieldType> createInstanceTypeProcessingchargeamount(FieldType value) {
        return new JAXBElement<FieldType>(_InstanceTypeProcessingchargeamount_QNAME, FieldType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "processingchargecurrency", scope = InstanceType.class)
    public JAXBElement<FieldType> createInstanceTypeProcessingchargecurrency(FieldType value) {
        return new JAXBElement<FieldType>(_InstanceTypeProcessingchargecurrency_QNAME, FieldType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FieldType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "refereed", scope = InstanceType.class)
    public JAXBElement<FieldType> createInstanceTypeRefereed(FieldType value) {
        return new JAXBElement<FieldType>(_InstanceTypeRefereed_QNAME, FieldType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelToType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RelToType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "to", scope = RelType.class)
    public JAXBElement<RelToType> createRelTypeTo(RelToType value) {
        return new JAXBElement<RelToType>(_RelTypeTo_QNAME, RelToType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "title", scope = RelType.class)
    public JAXBElement<String> createRelTypeTitle(String value) {
        return new JAXBElement<String>(_ResultTitle_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "websiteurl", scope = RelType.class)
    public JAXBElement<Object> createRelTypeWebsiteurl(Object value) {
        return new JAXBElement<Object>(_OrganizationWebsiteurl_QNAME, Object.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "officialname", scope = RelType.class)
    public JAXBElement<String> createRelTypeOfficialname(String value) {
        return new JAXBElement<String>(_DatasourceOfficialname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "datasourcetype", scope = RelType.class)
    public JAXBElement<QualifierType> createRelTypeDatasourcetype(QualifierType value) {
        return new JAXBElement<QualifierType>(_DatasourceDatasourcetype_QNAME, QualifierType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "collectedfrom", scope = RelType.class)
    public JAXBElement<NamedIdElementType> createRelTypeCollectedfrom(NamedIdElementType value) {
        return new JAXBElement<NamedIdElementType>(_ResultCollectedfrom_QNAME, NamedIdElementType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "url", scope = RelType.class)
    public JAXBElement<String> createRelTypeUrl(String value) {
        return new JAXBElement<String>(_RelTypeUrl_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "pid", scope = RelType.class)
    public JAXBElement<StructuredPropertyElementType> createRelTypePid(StructuredPropertyElementType value) {
        return new JAXBElement<StructuredPropertyElementType>(_ResultPid_QNAME, StructuredPropertyElementType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "dateofacceptance", scope = RelType.class)
    public JAXBElement<String> createRelTypeDateofacceptance(String value) {
        return new JAXBElement<String>(_ResultDateofacceptance_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "publisher", scope = RelType.class)
    public JAXBElement<String> createRelTypePublisher(String value) {
        return new JAXBElement<String>(_ResultPublisher_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "resulttype", scope = RelType.class)
    public JAXBElement<String> createRelTypeResulttype(String value) {
        return new JAXBElement<String>(_ResultResulttype_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "similarity", scope = RelType.class)
    public JAXBElement<Double> createRelTypeSimilarity(Double value) {
        return new JAXBElement<Double>(_RelTypeSimilarity_QNAME, Double.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "type", scope = RelType.class)
    public JAXBElement<String> createRelTypeType(String value) {
        return new JAXBElement<String>(_RelTypeType_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "code", scope = RelType.class)
    public JAXBElement<String> createRelTypeCode(String value) {
        return new JAXBElement<String>(_RelTypeCode_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "acronym", scope = RelType.class)
    public JAXBElement<String> createRelTypeAcronym(String value) {
        return new JAXBElement<String>(_RelTypeAcronym_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalname", scope = RelType.class)
    public JAXBElement<String> createRelTypeLegalname(String value) {
        return new JAXBElement<String>(_OrganizationLegalname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "legalshortname", scope = RelType.class)
    public JAXBElement<String> createRelTypeLegalshortname(String value) {
        return new JAXBElement<String>(_OrganizationLegalshortname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "country", scope = RelType.class)
    public JAXBElement<String> createRelTypeCountry(String value) {
        return new JAXBElement<String>(_ResultCountry_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "contracttype", scope = RelType.class)
    public JAXBElement<QualifierType> createRelTypeContracttype(QualifierType value) {
        return new JAXBElement<QualifierType>(_RelTypeContracttype_QNAME, QualifierType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingFlatType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundingFlatType }{@code >}
     */
    @XmlElementDecl(namespace = "http://namespace.openaire.eu/oaf", name = "funding", scope = RelType.class)
    public JAXBElement<FundingFlatType> createRelTypeFunding(FundingFlatType value) {
        return new JAXBElement<FundingFlatType>(_RelTypeFunding_QNAME, FundingFlatType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "funding_level_2", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel2(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel2_QNAME, FundingType.class, FundingTreeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "funding_level_1", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel1(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel1_QNAME, FundingType.class, FundingTreeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "funding_level_0", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel0(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel0_QNAME, FundingType.class, FundingTreeType.class, value);
    }

}
