//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 04:31:46 PM UTC 
//


package eu.openaire.oaf.model.base;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element name="to" type="{http://namespace.openaire.eu/oaf}relToType"/&gt;
 *           &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="websiteurl" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *           &lt;choice&gt;
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relDataSourceGroup"/&gt;
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relResultGroup"/&gt;
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relProjectGroup"/&gt;
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}relOrganizationGroup"/&gt;
 *             &lt;group ref="{http://namespace.openaire.eu/oaf}fundingGroup"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://namespace.openaire.eu/oaf}dataInfoAttributeGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relType", propOrder = {
    "toOrTitleOrWebsiteurl"
})
public class RelType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRefs({
        @XmlElementRef(name = "to", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "title", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "websiteurl", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "officialname", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datasourcetype", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "collectedfrom", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "url", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pid", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dateofacceptance", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "resulttype", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "similarity", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "type", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "code", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "acronym", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "legalname", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "legalshortname", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "country", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contracttype", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "funding", namespace = "http://namespace.openaire.eu/oaf", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> toOrTitleOrWebsiteurl;
    @XmlAttribute(name = "inferred")
    protected Boolean inferred;
    @XmlAttribute(name = "trust")
    protected String trust;
    @XmlAttribute(name = "inferenceprovenance")
    protected String inferenceprovenance;
    @XmlAttribute(name = "classid", required = true)
    protected String classid;
    @XmlAttribute(name = "classname", required = true)
    protected String classname;
    @XmlAttribute(name = "schemeid", required = true)
    protected String schemeid;
    @XmlAttribute(name = "schemename", required = true)
    protected String schemename;

    /**
     * Gets the value of the toOrTitleOrWebsiteurl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toOrTitleOrWebsiteurl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToOrTitleOrWebsiteurl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link RelToType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link NamedIdElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link StructuredPropertyElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link FundingFlatType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getToOrTitleOrWebsiteurl() {
        if (toOrTitleOrWebsiteurl == null) {
            toOrTitleOrWebsiteurl = new ArrayList<JAXBElement<?>>();
        }
        return this.toOrTitleOrWebsiteurl;
    }

    /**
     * Gets the value of the inferred property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInferred() {
        return inferred;
    }

    /**
     * Sets the value of the inferred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInferred(Boolean value) {
        this.inferred = value;
    }

    /**
     * Gets the value of the trust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrust() {
        return trust;
    }

    /**
     * Sets the value of the trust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrust(String value) {
        this.trust = value;
    }

    /**
     * Gets the value of the inferenceprovenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInferenceprovenance() {
        return inferenceprovenance;
    }

    /**
     * Sets the value of the inferenceprovenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInferenceprovenance(String value) {
        this.inferenceprovenance = value;
    }

    /**
     * Gets the value of the classid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassid() {
        return classid;
    }

    /**
     * Sets the value of the classid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassid(String value) {
        this.classid = value;
    }

    /**
     * Gets the value of the classname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassname() {
        return classname;
    }

    /**
     * Sets the value of the classname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassname(String value) {
        this.classname = value;
    }

    /**
     * Gets the value of the schemeid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeid() {
        return schemeid;
    }

    /**
     * Sets the value of the schemeid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeid(String value) {
        this.schemeid = value;
    }

    /**
     * Gets the value of the schemename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemename() {
        return schemename;
    }

    /**
     * Sets the value of the schemename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemename(String value) {
        this.schemename = value;
    }

}
